### ISSUE TITLE
Land Surface Temperature does not seem to be working 

### ISSUE THREAD

**Issue by tjquinn1** [sacridini/GEET#1]
I have been trying to calculate land surface temp for landsat 8. I have was able to add all the band without error. When I try to map the LST band I just get a solid blue box. I am not sure if this is an error or if I am missing something. 

```
var geet = require('users/elacerda/geet:geet'); 

 var image2 = ee.Image(
  l82.filterBounds(point)
    .filterDate('2018-07-01', '2018-7-31')
    .sort('CLOUD_COVER')
    .first()
);
var new_toa_radiance = geet.toa_radiance(image2, 10);
var brightness_temp_img = geet.brightness_temp_l8c(new_toa_radiance, true);
var l8_ndvi = geet.ndvi_l8(brightness_temp_img); 
var img_pv = geet.prop_veg(l8_ndvi);
var lse = geet.surface_emissivity(img_pv);
var surfTemp_img = geet.surface_temperature_oli(lse);
var im = surfTemp_img.select("LST");
print(im);
Map.addLayer(im, {palette: ['blue', 'green', 'red']});
```

**Comment by tjquinn1** [comment]
Issue was my problem, I needed to add a stretch to the image.

**Comment by sacridini** [comment]
Hi! 
The code is right.
Make sure your are using the Landsat RAW images! 
And that after you plot the image you need to set the range of visualization manualy to "Stretch 100%" or something like that. You can do that in the "Layers" button on the map visualization window. If you export the result as an imagem (tif) and load into QGIS you dont need to configure the range, the software will do that for you. :) 

Try to do that and tell me the results! 
Bye!

**Comment by tjquinn1** [comment]
Thanks for the response Eduardo. The stretch did work. When using the docs I noticed some spelling errors such as brightness temperature was "bribrightness", would it be alright if I fixed the errors and raised a pull request? This is a cool project and I would like to to contribute where I can.

**Comment by sacridini** [comment]
Yeah, sure! It would be very nice to have more people contributing to the project :) 
Thanks!
