### ISSUE TITLE
Scaling factor for Sentinel 2 imagery

### ISSUE THREAD

**Issue by mariofajardo** [sacridini/GEET#3]
Just a heads up about some indices for Sentinel 2 data (both surface reflecteance and TOA)

Since they need to be scaled by a factor of 10000.

More details in [here](https://gis.stackexchange.com/questions/173145/radiometric-calibration-of-sentinel-2-products/173725#173725)

So...for example the EVI index should be:

'2.5 * ((NIR - RED) / (NIR + 6 * RED - 7.5 * BLUE + 10000))'

instead of

'2.5 * ((NIR - RED) / (NIR + 6 * RED - 7.5 * BLUE + 1))'

in order to get sensible values

Cheers,

Mario

**Comment by sacridini** [comment]
Fixed. Thanks!
